#Parse the smt2 files generated by KLEE
#Create the disjunction and solve it
import os
import z3
import sys
import re

def parse_file(file,constraint_list):
    #Gets the constraint in the smt2 file
    f=z3.parse_smt2_file(file)
    for constraint in f:
        constraint_list.append(constraint)
    return constraint_list

if __name__=='__main__':
    #Assuming there is no constraints related to the value of the variables
    s=z3.Solver()
    dir=sys.argv[1]
    constraint_list=[]
    for file in os.listdir(dir):
        f=os.path.join(dir,file)
        if ".smt2" in f:
            constraint_list=parse_file(f,constraint_list)
    
    s.add(z3.Not(z3.Or(*constraint_list)))
    print(s.assertions())
    result = s.check()
    if result == z3.sat:
        m=s.model()
        print(m)
        #Use sexpr to get the solution in the smt2 format
        #print(m.sexpr())
    print(result)
    